import React, { useState, useEffect, useMemo } from 'react';
import { useApp } from '../../context/AppContext';
import { api } from '../../services/api';
import { CategoryItem } from '../../types';
import {
  Layers,
  Search,
  Plus,
  Trash2,
  Edit2,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  RefreshCw,
  X,
  Package,
  FolderTree,
  Calendar,
  Image as ImageIcon
} from 'lucide-react';

interface CategoryManagementProps {
  onCategorySelectedForSubcategories?: (categoryId: string) => void;
}

export const CategoryManagement: React.FC<CategoryManagementProps> = ({
  onCategorySelectedForSubcategories,
}) => {
  const { categories, refreshCategories, refreshSubcategories, refreshProducts } = useApp();

  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'inactive'>('all');
  const [loading, setLoading] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<CategoryItem | null>(null);
  const [formData, setFormData] = useState({
    name: '',
    slug: '',
    description: '',
    image: '',
    status: true,
  });
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);

  // Delete Confirmation Modal
  const [deletingCategory, setDeletingCategory] = useState<CategoryItem | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const showNotification = (type: 'success' | 'error', msg: string) => {
    if (type === 'success') {
      setActionSuccess(msg);
      setTimeout(() => setActionSuccess(null), 4000);
    } else {
      setActionError(msg);
      setTimeout(() => setActionError(null), 5000);
    }
  };

  const handleRefresh = async () => {
    setLoading(true);
    try {
      await refreshCategories();
      showNotification('success', 'Categories updated from server');
    } catch (err: any) {
      showNotification('error', err.message || 'Failed to refresh categories');
    } finally {
      setLoading(false);
    }
  };

  const generateSlug = (name: string) => {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/[\s_-]+/g, '-')
      .replace(/^-+|-+$/g, '');
  };

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setFormData((prev) => ({
      ...prev,
      name: val,
      slug: slugAutoGenerated ? generateSlug(val) : prev.slug,
    }));
  };

  const openCreateModal = () => {
    setEditingCategory(null);
    setFormData({
      name: '',
      slug: '',
      description: '',
      image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      status: true,
    });
    setSlugAutoGenerated(true);
    setActionError(null);
    setIsModalOpen(true);
  };

  const openEditModal = (category: CategoryItem) => {
    setEditingCategory(category);
    setFormData({
      name: category.name,
      slug: category.slug,
      description: category.description || '',
      image: category.image || '',
      status: category.status !== false,
    });
    setSlugAutoGenerated(false);
    setActionError(null);
    setIsModalOpen(true);
  };

  const handleSaveCategory = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim()) {
      showNotification('error', 'Category name is required');
      return;
    }

    setLoading(true);
    try {
      if (editingCategory) {
        await api.updateCategory(editingCategory.id || editingCategory._id!, formData);
        showNotification('success', `Category "${formData.name}" updated successfully`);
      } else {
        await api.createCategory(formData);
        showNotification('success', `Category "${formData.name}" created successfully`);
      }
      setIsModalOpen(false);
      await refreshCategories();
      await refreshProducts();
    } catch (err: any) {
      showNotification('error', err.message || 'Error saving category');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleStatus = async (category: CategoryItem) => {
    const catId = category.id || category._id!;
    try {
      const res = await api.toggleCategoryStatus(catId);
      showNotification(
        'success',
        `Category "${res.category.name}" is now ${res.category.status ? 'Active' : 'Inactive'}`
      );
      await refreshCategories();
    } catch (err: any) {
      showNotification('error', err.message || 'Failed to toggle category status');
    }
  };

  const confirmDeleteCategory = async () => {
    if (!deletingCategory) return;
    setIsDeleting(true);
    const catId = deletingCategory.id || deletingCategory._id!;
    try {
      await api.deleteCategory(catId);
      showNotification('success', `Category "${deletingCategory.name}" removed successfully`);
      setDeletingCategory(null);
      await refreshCategories();
      await refreshSubcategories();
      await refreshProducts();
    } catch (err: any) {
      showNotification('error', err.message || 'Could not delete category');
    } finally {
      setIsDeleting(false);
    }
  };

  // Filter Categories
  const filteredCategories = useMemo(() => {
    return (categories || []).filter((cat) => {
      const matchesSearch =
        cat.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        cat.slug.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (cat.description && cat.description.toLowerCase().includes(searchQuery.toLowerCase()));

      const matchesStatus =
        statusFilter === 'all' ||
        (statusFilter === 'active' && cat.status !== false) ||
        (statusFilter === 'inactive' && cat.status === false);

      return matchesSearch && matchesStatus;
    });
  }, [categories, searchQuery, statusFilter]);

  return (
    <div className="space-y-5">
      {/* Top Banner & Action Controls */}
      <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
        <div>
          <h3 className="font-['Montserrat'] font-bold text-lg text-[#1a1c1c] flex items-center gap-2">
            <Layers className="w-5 h-5 text-[#0058be]" />
            <span>Category Management</span>
          </h3>
          <p className="text-xs text-[#555f6f] mt-0.5">
            Organize catalog products into primary categories and establish navigation hierarchy
          </p>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          <button
            type="button"
            onClick={handleRefresh}
            disabled={loading}
            className="p-2 bg-white hover:bg-[#f0f0f2] border border-[#e2e2e2] rounded-xl text-xs font-semibold text-[#424754] transition-colors flex items-center gap-1.5"
            title="Refresh categories"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            <span className="hidden sm:inline">Sync</span>
          </button>

          <button
            type="button"
            onClick={openCreateModal}
            id="btn-add-category"
            className="flex-1 sm:flex-none px-4 py-2 bg-[#0058be] hover:bg-[#2170e4] text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 shadow-sm transition-colors cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>Add Category</span>
          </button>
        </div>
      </div>

      {/* Notifications */}
      {actionSuccess && (
        <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-emerald-800 text-xs font-medium flex items-center gap-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0" />
          <span>{actionSuccess}</span>
        </div>
      )}

      {actionError && (
        <div className="p-3 bg-red-50 border border-red-200 rounded-xl text-red-800 text-xs font-medium flex items-center gap-2 animate-in fade-in">
          <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0" />
          <span>{actionError}</span>
        </div>
      )}

      {/* Filter and Search Bar */}
      <div className="bg-white p-3.5 rounded-2xl border border-[#e2e2e2] shadow-xs flex flex-col sm:flex-row gap-3 items-center justify-between">
        <div className="relative w-full sm:w-80">
          <Search className="w-4 h-4 text-[#727785] absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search categories by name, slug, or description..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#0058be]"
          />
        </div>

        <div className="flex items-center gap-1.5 self-end sm:self-center">
          <span className="text-xs text-[#727785] font-medium mr-1">Status:</span>
          {(['all', 'active', 'inactive'] as const).map((filter) => (
            <button
              key={filter}
              type="button"
              onClick={() => setStatusFilter(filter)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold capitalize transition-colors ${
                statusFilter === filter
                  ? 'bg-[#0058be] text-white shadow-xs'
                  : 'bg-[#f0f0f2] text-[#555f6f] hover:bg-[#e4e4e7]'
              }`}
            >
              {filter}
            </button>
          ))}
        </div>
      </div>

      {/* Categories Table / Card View */}
      <div className="bg-white rounded-2xl border border-[#e2e2e2] shadow-xs overflow-hidden">
        {filteredCategories.length === 0 ? (
          <div className="p-10 text-center space-y-2">
            <Layers className="w-10 h-10 text-[#a1a5b0] mx-auto" />
            <h4 className="font-bold text-sm text-[#1a1c1c]">No Categories Found</h4>
            <p className="text-xs text-[#555f6f] max-w-sm mx-auto">
              {searchQuery || statusFilter !== 'all'
                ? 'No categories match your current search or status filter.'
                : 'No categories have been added yet. Click "Add Category" above to get started.'}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#f9f9f9] text-[#727785] uppercase tracking-wider font-semibold border-b border-[#eeeeee]">
                <tr>
                  <th className="px-5 py-3.5">Category Info</th>
                  <th className="px-5 py-3.5">Slug</th>
                  <th className="px-5 py-3.5">Linked Products</th>
                  <th className="px-5 py-3.5">Subcategories</th>
                  <th className="px-5 py-3.5">Status</th>
                  <th className="px-5 py-3.5">Created Date</th>
                  <th className="px-5 py-3.5 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#eeeeee]">
                {filteredCategories.map((cat) => {
                  const catId = cat.id || cat._id!;
                  const isActive = cat.status !== false;
                  return (
                    <tr key={catId} className="hover:bg-[#f9f9f9]/80 transition-colors">
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-3">
                          {cat.image ? (
                            <img
                              src={cat.image}
                              alt={cat.name}
                              className="w-10 h-10 rounded-lg object-cover bg-[#eeeeee] border border-[#e2e2e2] flex-shrink-0"
                            />
                          ) : (
                            <div className="w-10 h-10 rounded-lg bg-[#d8e2ff]/50 text-[#0058be] flex items-center justify-center flex-shrink-0 font-bold text-sm">
                              {cat.name.charAt(0)}
                            </div>
                          )}
                          <div className="min-w-0">
                            <div className="font-bold text-sm text-[#1a1c1c] truncate">{cat.name}</div>
                            {cat.description && (
                              <div className="text-[11px] text-[#727785] line-clamp-1 max-w-xs mt-0.5">
                                {cat.description}
                              </div>
                            )}
                          </div>
                        </div>
                      </td>

                      <td className="px-5 py-3.5">
                        <code className="text-[11px] bg-[#eeeeee] text-[#424754] px-2 py-0.5 rounded font-mono">
                          {cat.slug}
                        </code>
                      </td>

                      <td className="px-5 py-3.5">
                        <span className="inline-flex items-center gap-1 font-semibold text-[#1a1c1c]">
                          <Package className="w-3.5 h-3.5 text-[#727785]" />
                          <span>{cat.productCount ?? 0}</span>
                        </span>
                      </td>

                      <td className="px-5 py-3.5">
                        <button
                          type="button"
                          onClick={() => onCategorySelectedForSubcategories && onCategorySelectedForSubcategories(catId)}
                          className="inline-flex items-center gap-1 font-semibold text-[#0058be] hover:underline"
                          title="View subcategories for this category"
                        >
                          <FolderTree className="w-3.5 h-3.5 text-[#0058be]" />
                          <span>{cat.subcategoriesCount ?? 0}</span>
                        </button>
                      </td>

                      <td className="px-5 py-3.5">
                        <button
                          type="button"
                          onClick={() => handleToggleStatus(cat)}
                          className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase transition-all ${
                            isActive
                              ? 'bg-emerald-100 text-emerald-800 hover:bg-emerald-200'
                              : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
                          }`}
                          title="Click to toggle status"
                        >
                          {isActive ? (
                            <>
                              <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                              <span>Active</span>
                            </>
                          ) : (
                            <>
                              <XCircle className="w-3 h-3 text-zinc-500" />
                              <span>Inactive</span>
                            </>
                          )}
                        </button>
                      </td>

                      <td className="px-5 py-3.5 text-[#727785]">
                        <div className="flex items-center gap-1 text-[11px]">
                          <Calendar className="w-3 h-3" />
                          <span>{cat.createdAt ? new Date(cat.createdAt).toLocaleDateString() : 'Initial'}</span>
                        </div>
                      </td>

                      <td className="px-5 py-3.5 text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          <button
                            type="button"
                            onClick={() => openEditModal(cat)}
                            className="p-1.5 text-[#555f6f] hover:text-[#0058be] hover:bg-[#d8e2ff]/40 rounded-lg transition-colors"
                            title="Edit Category"
                          >
                            <Edit2 className="w-3.5 h-3.5" />
                          </button>
                          <button
                            type="button"
                            onClick={() => setDeletingCategory(cat)}
                            className="p-1.5 text-[#ba1a1a] hover:bg-red-50 rounded-lg transition-colors"
                            title="Delete Category"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ================= MODAL: ADD / EDIT CATEGORY ================= */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-white rounded-2xl shadow-2xl border border-[#e2e2e2] w-full max-w-md overflow-hidden"
          >
            <div className="p-5 bg-[#f9f9f9] border-b border-[#eeeeee] flex items-center justify-between">
              <h3 className="font-['Montserrat'] font-bold text-base text-[#1a1c1c] flex items-center gap-2">
                <Layers className="w-4 h-4 text-[#0058be]" />
                <span>{editingCategory ? 'Edit Category' : 'Add New Category'}</span>
              </h3>
              <button
                type="button"
                onClick={() => setIsModalOpen(false)}
                className="w-7 h-7 rounded-full bg-[#eeeeee] flex items-center justify-center hover:bg-[#e2e2e2] text-[#424754]"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleSaveCategory} className="p-5 space-y-4">
              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1">
                  Category Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Drinkware, Hats, Office Supplies"
                  value={formData.name}
                  onChange={handleNameChange}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#0058be]"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="text-xs font-bold text-[#1a1c1c]">
                    Slug / URL Identifier <span className="text-red-500">*</span>
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      setSlugAutoGenerated(true);
                      setFormData((prev) => ({ ...prev, slug: generateSlug(prev.name) }));
                    }}
                    className="text-[10px] text-[#0058be] hover:underline"
                  >
                    Auto-generate
                  </button>
                </div>
                <input
                  type="text"
                  required
                  placeholder="e.g. drinkware, hats"
                  value={formData.slug}
                  onChange={(e) => {
                    setSlugAutoGenerated(false);
                    setFormData({ ...formData, slug: e.target.value.toLowerCase().replace(/\s+/g, '-') });
                  }}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs font-mono focus:outline-none focus:ring-2 focus:ring-[#0058be]"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1">Description</label>
                <textarea
                  rows={2}
                  placeholder="Brief description of this product category..."
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#0058be]"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1 flex items-center gap-1.5">
                  <ImageIcon className="w-3.5 h-3.5 text-[#727785]" />
                  <span>Image URL (Optional)</span>
                </label>
                <input
                  type="url"
                  placeholder="https://..."
                  value={formData.image}
                  onChange={(e) => setFormData({ ...formData, image: e.target.value })}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#0058be]"
                />
                {formData.image && (
                  <div className="mt-2 w-16 h-16 rounded-lg border border-[#e2e2e2] overflow-hidden bg-[#eeeeee]">
                    <img
                      src={formData.image}
                      alt="Preview"
                      className="w-full h-full object-cover"
                      onError={(e) => {
                        (e.target as HTMLElement).style.display = 'none';
                      }}
                    />
                  </div>
                )}
              </div>

              <div className="flex items-center justify-between p-3 bg-[#f9f9f9] rounded-xl border border-[#e2e2e2]">
                <div>
                  <div className="text-xs font-bold text-[#1a1c1c]">Category Status</div>
                  <div className="text-[11px] text-[#727785]">Visible in navigation and product catalog</div>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    checked={formData.status}
                    onChange={(e) => setFormData({ ...formData, status: e.target.checked })}
                    className="sr-only peer"
                  />
                  <div className="w-9 h-5 bg-[#d0d3d8] peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-[#d0d3d8] after:border after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-[#0058be]"></div>
                </label>
              </div>

              <div className="flex gap-2 pt-3 border-t border-[#eeeeee]">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="flex-1 py-2 rounded-xl bg-[#eeeeee] hover:bg-[#e2e2e2] text-[#1a1c1c] text-xs font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 py-2 rounded-xl bg-[#0058be] hover:bg-[#2170e4] text-white text-xs font-semibold flex items-center justify-center gap-1.5 shadow-sm transition-colors"
                >
                  {loading && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
                  <span>{editingCategory ? 'Save Changes' : 'Create Category'}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ================= MODAL: DELETE PROTECTION / CONFIRMATION ================= */}
      {deletingCategory && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-white rounded-2xl shadow-2xl border border-[#e2e2e2] w-full max-w-md p-6 space-y-4"
          >
            <div className="w-12 h-12 rounded-full bg-red-100 text-red-600 flex items-center justify-center mx-auto">
              <AlertTriangle className="w-6 h-6" />
            </div>

            <div className="text-center space-y-1.5">
              <h3 className="font-['Montserrat'] font-bold text-base text-[#1a1c1c]">
                Delete Category "{deletingCategory.name}"?
              </h3>
              <p className="text-xs text-[#555f6f] leading-relaxed">
                This will permanently remove the category from the database.
              </p>
            </div>

            {/* Dependency Warning */}
            {((deletingCategory.productCount ?? 0) > 0 || (deletingCategory.subcategoriesCount ?? 0) > 0) ? (
              <div className="p-3.5 bg-amber-50 border border-amber-200 rounded-xl space-y-2 text-xs text-amber-900">
                <div className="font-bold flex items-center gap-1.5 text-amber-800">
                  <AlertTriangle className="w-4 h-4 text-amber-600" />
                  <span>Relationship Protection Triggered</span>
                </div>
                <p className="text-[11px] leading-relaxed">
                  This category cannot be deleted while linked records exist:
                </p>
                <ul className="list-disc list-inside space-y-0.5 text-[11px] font-medium pl-1">
                  {(deletingCategory.productCount ?? 0) > 0 && (
                    <li>
                      <strong>{deletingCategory.productCount}</strong> existing product(s) reference this category
                    </li>
                  )}
                  {(deletingCategory.subcategoriesCount ?? 0) > 0 && (
                    <li>
                      <strong>{deletingCategory.subcategoriesCount}</strong> subcategory(ies) belong to this category
                    </li>
                  )}
                </ul>
                <p className="text-[11px] text-amber-800 italic pt-1">
                  Please reassign or delete these products and subcategories first before deleting this category.
                </p>
              </div>
            ) : (
              <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-xs text-emerald-800">
                No active products or subcategories are linked to this category. It is safe to delete.
              </div>
            )}

            <div className="flex gap-2 pt-2">
              <button
                type="button"
                onClick={() => setDeletingCategory(null)}
                className="flex-1 py-2 rounded-xl bg-[#eeeeee] hover:bg-[#e2e2e2] text-[#1a1c1c] text-xs font-semibold"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={confirmDeleteCategory}
                disabled={isDeleting}
                className="flex-1 py-2 rounded-xl bg-[#ba1a1a] hover:bg-red-700 text-white text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors disabled:opacity-50"
              >
                {isDeleting && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
                <span>Delete Category</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
