import React, { useState, useMemo } from 'react';
import { useApp } from '../../context/AppContext';
import { api } from '../../services/api';
import { SubcategoryItem } from '../../types';
import {
  FolderTree,
  Search,
  Plus,
  Trash2,
  Edit2,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  RefreshCw,
  X,
  Package,
  Calendar,
  Layers,
  Image as ImageIcon
} from 'lucide-react';

interface SubcategoryManagementProps {
  initialCategoryId?: string | null;
}

export const SubcategoryManagement: React.FC<SubcategoryManagementProps> = ({
  initialCategoryId,
}) => {
  const { categories, subcategories, refreshSubcategories, refreshProducts } = useApp();

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategoryFilter, setSelectedCategoryFilter] = useState<string>(
    initialCategoryId || 'all'
  );
  const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'inactive'>('all');
  const [loading, setLoading] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingSubcategory, setEditingSubcategory] = useState<SubcategoryItem | null>(null);
  const [formData, setFormData] = useState({
    name: '',
    category: '',
    slug: '',
    description: '',
    image: '',
    status: true,
  });
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);

  // Delete Confirmation Modal
  const [deletingSubcategory, setDeletingSubcategory] = useState<SubcategoryItem | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const showNotification = (type: 'success' | 'error', msg: string) => {
    if (type === 'success') {
      setActionSuccess(msg);
      setTimeout(() => setActionSuccess(null), 4000);
    } else {
      setActionError(msg);
      setTimeout(() => setActionError(null), 5000);
    }
  };

  const handleRefresh = async () => {
    setLoading(true);
    try {
      await refreshSubcategories();
      showNotification('success', 'Subcategories synced from server');
    } catch (err: any) {
      showNotification('error', err.message || 'Failed to refresh subcategories');
    } finally {
      setLoading(false);
    }
  };

  const generateSlug = (name: string) => {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/[\s_-]+/g, '-')
      .replace(/^-+|-+$/g, '');
  };

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setFormData((prev) => ({
      ...prev,
      name: val,
      slug: slugAutoGenerated ? generateSlug(val) : prev.slug,
    }));
  };

  const openCreateModal = () => {
    // Default to the currently filtered category if not 'all', otherwise first category
    const defaultCatId =
      selectedCategoryFilter !== 'all'
        ? selectedCategoryFilter
        : categories && categories.length > 0
        ? categories[0].id || categories[0]._id!
        : '';

    setEditingSubcategory(null);
    setFormData({
      name: '',
      category: defaultCatId,
      slug: '',
      description: '',
      image: '',
      status: true,
    });
    setSlugAutoGenerated(true);
    setActionError(null);
    setIsModalOpen(true);
  };

  const openEditModal = (subcat: SubcategoryItem) => {
    setEditingSubcategory(subcat);
    const catId = typeof subcat.category === 'object' ? (subcat.category.id || subcat.category._id!) : subcat.category;
    setFormData({
      name: subcat.name,
      category: catId,
      slug: subcat.slug,
      description: subcat.description || '',
      image: subcat.image || '',
      status: subcat.status !== false,
    });
    setSlugAutoGenerated(false);
    setActionError(null);
    setIsModalOpen(true);
  };

  const handleSaveSubcategory = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim()) {
      showNotification('error', 'Subcategory name is required');
      return;
    }
    if (!formData.category) {
      showNotification('error', 'Please select a parent category');
      return;
    }

    setLoading(true);
    try {
      if (editingSubcategory) {
        await api.updateSubcategory(editingSubcategory.id || editingSubcategory._id!, formData);
        showNotification('success', `Subcategory "${formData.name}" updated successfully`);
      } else {
        await api.createSubcategory(formData);
        showNotification('success', `Subcategory "${formData.name}" created successfully`);
      }
      setIsModalOpen(false);
      await refreshSubcategories();
      await refreshProducts();
    } catch (err: any) {
      showNotification('error', err.message || 'Error saving subcategory');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleStatus = async (subcat: SubcategoryItem) => {
    const subcatId = subcat.id || subcat._id!;
    try {
      const res = await api.toggleSubcategoryStatus(subcatId);
      showNotification(
        'success',
        `Subcategory "${res.subcategory.name}" is now ${res.subcategory.status ? 'Active' : 'Inactive'}`
      );
      await refreshSubcategories();
    } catch (err: any) {
      showNotification('error', err.message || 'Failed to toggle subcategory status');
    }
  };

  const confirmDeleteSubcategory = async () => {
    if (!deletingSubcategory) return;
    setIsDeleting(true);
    const subcatId = deletingSubcategory.id || deletingSubcategory._id!;
    try {
      await api.deleteSubcategory(subcatId);
      showNotification('success', `Subcategory "${deletingSubcategory.name}" removed successfully`);
      setDeletingSubcategory(null);
      await refreshSubcategories();
      await refreshProducts();
    } catch (err: any) {
      showNotification('error', err.message || 'Could not delete subcategory');
    } finally {
      setIsDeleting(false);
    }
  };

  // Filter Subcategories
  const filteredSubcategories = useMemo(() => {
    return (subcategories || []).filter((sub) => {
      // Category filter
      const parentCatId = typeof sub.category === 'object' ? (sub.category.id || sub.category._id!) : sub.category;
      const parentCatName = typeof sub.category === 'object' ? sub.category.name : '';
      
      const matchesCategory =
        selectedCategoryFilter === 'all' ||
        parentCatId === selectedCategoryFilter ||
        parentCatName === selectedCategoryFilter;

      // Status filter
      const matchesStatus =
        statusFilter === 'all' ||
        (statusFilter === 'active' && sub.status !== false) ||
        (statusFilter === 'inactive' && sub.status === false);

      // Search query
      const matchesSearch =
        sub.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        sub.slug.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (sub.description && sub.description.toLowerCase().includes(searchQuery.toLowerCase())) ||
        (parentCatName && parentCatName.toLowerCase().includes(searchQuery.toLowerCase()));

      return matchesCategory && matchesStatus && matchesSearch;
    });
  }, [subcategories, selectedCategoryFilter, statusFilter, searchQuery]);

  return (
    <div className="space-y-5">
      {/* Top Banner & Action Controls */}
      <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
        <div>
          <h3 className="font-['Montserrat'] font-bold text-lg text-[#1a1c1c] flex items-center gap-2">
            <FolderTree className="w-5 h-5 text-[#6b38d4]" />
            <span>Subcategory Management</span>
          </h3>
          <p className="text-xs text-[#555f6f] mt-0.5">
            Refine primary categories into focused sub-groupings with dynamic product associations
          </p>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          <button
            type="button"
            onClick={handleRefresh}
            disabled={loading}
            className="p-2 bg-white hover:bg-[#f0f0f2] border border-[#e2e2e2] rounded-xl text-xs font-semibold text-[#424754] transition-colors flex items-center gap-1.5"
            title="Refresh subcategories"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            <span className="hidden sm:inline">Sync</span>
          </button>

          <button
            type="button"
            onClick={openCreateModal}
            id="btn-add-subcategory"
            className="flex-1 sm:flex-none px-4 py-2 bg-[#6b38d4] hover:bg-[#582db5] text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 shadow-sm transition-colors cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>Add Subcategory</span>
          </button>
        </div>
      </div>

      {/* Notifications */}
      {actionSuccess && (
        <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-emerald-800 text-xs font-medium flex items-center gap-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0" />
          <span>{actionSuccess}</span>
        </div>
      )}

      {actionError && (
        <div className="p-3 bg-red-50 border border-red-200 rounded-xl text-red-800 text-xs font-medium flex items-center gap-2 animate-in fade-in">
          <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0" />
          <span>{actionError}</span>
        </div>
      )}

      {/* Filter and Search Bar */}
      <div className="bg-white p-3.5 rounded-2xl border border-[#e2e2e2] shadow-xs flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between">
        <div className="flex flex-col sm:flex-row gap-2.5 items-stretch sm:items-center flex-1">
          {/* Search Box */}
          <div className="relative flex-1 max-w-xs">
            <Search className="w-4 h-4 text-[#727785] absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search subcategories..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
            />
          </div>

          {/* Parent Category Filter Dropdown */}
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-[#727785] font-medium whitespace-nowrap">Category:</span>
            <select
              value={selectedCategoryFilter}
              onChange={(e) => setSelectedCategoryFilter(e.target.value)}
              className="px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs font-medium text-[#1a1c1c] focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
            >
              <option value="all">All Categories ({categories.length})</option>
              {categories.map((c) => (
                <option key={c.id || c._id} value={c.id || c._id}>
                  {c.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Status Toggle Buttons */}
        <div className="flex items-center gap-1.5 self-end md:self-center">
          <span className="text-xs text-[#727785] font-medium mr-1">Status:</span>
          {(['all', 'active', 'inactive'] as const).map((filter) => (
            <button
              key={filter}
              type="button"
              onClick={() => setStatusFilter(filter)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold capitalize transition-colors ${
                statusFilter === filter
                  ? 'bg-[#6b38d4] text-white shadow-xs'
                  : 'bg-[#f0f0f2] text-[#555f6f] hover:bg-[#e4e4e7]'
              }`}
            >
              {filter}
            </button>
          ))}
        </div>
      </div>

      {/* Subcategories Table */}
      <div className="bg-white rounded-2xl border border-[#e2e2e2] shadow-xs overflow-hidden">
        {filteredSubcategories.length === 0 ? (
          <div className="p-10 text-center space-y-2">
            <FolderTree className="w-10 h-10 text-[#a1a5b0] mx-auto" />
            <h4 className="font-bold text-sm text-[#1a1c1c]">No Subcategories Found</h4>
            <p className="text-xs text-[#555f6f] max-w-sm mx-auto">
              {searchQuery || selectedCategoryFilter !== 'all' || statusFilter !== 'all'
                ? 'No subcategories match your current search and filter settings.'
                : 'No subcategories have been created yet. Click "Add Subcategory" to add your first subcategory.'}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#f9f9f9] text-[#727785] uppercase tracking-wider font-semibold border-b border-[#eeeeee]">
                <tr>
                  <th className="px-5 py-3.5">Subcategory Name</th>
                  <th className="px-5 py-3.5">Parent Category</th>
                  <th className="px-5 py-3.5">Slug</th>
                  <th className="px-5 py-3.5">Linked Products</th>
                  <th className="px-5 py-3.5">Status</th>
                  <th className="px-5 py-3.5">Created Date</th>
                  <th className="px-5 py-3.5 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#eeeeee]">
                {filteredSubcategories.map((sub) => {
                  const subId = sub.id || sub._id!;
                  const isActive = sub.status !== false;
                  const parentName =
                    typeof sub.category === 'object'
                      ? sub.category?.name
                      : categories.find((c) => (c.id || c._id) === sub.category)?.name || 'Unknown';

                  return (
                    <tr key={subId} className="hover:bg-[#f9f9f9]/80 transition-colors">
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-3">
                          {sub.image ? (
                            <img
                              src={sub.image}
                              alt={sub.name}
                              className="w-10 h-10 rounded-lg object-cover bg-[#eeeeee] border border-[#e2e2e2] flex-shrink-0"
                            />
                          ) : (
                            <div className="w-10 h-10 rounded-lg bg-purple-50 text-[#6b38d4] flex items-center justify-center flex-shrink-0 font-bold text-sm">
                              {sub.name.charAt(0)}
                            </div>
                          )}
                          <div className="min-w-0">
                            <div className="font-bold text-sm text-[#1a1c1c] truncate">{sub.name}</div>
                            {sub.description && (
                              <div className="text-[11px] text-[#727785] line-clamp-1 max-w-xs mt-0.5">
                                {sub.description}
                              </div>
                            )}
                          </div>
                        </div>
                      </td>

                      <td className="px-5 py-3.5">
                        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-[#d8e2ff]/50 text-[#0058be] text-[11px] font-semibold">
                          <Layers className="w-3 h-3 text-[#0058be]" />
                          <span>{parentName}</span>
                        </span>
                      </td>

                      <td className="px-5 py-3.5">
                        <code className="text-[11px] bg-[#eeeeee] text-[#424754] px-2 py-0.5 rounded font-mono">
                          {sub.slug}
                        </code>
                      </td>

                      <td className="px-5 py-3.5">
                        <span className="inline-flex items-center gap-1 font-semibold text-[#1a1c1c]">
                          <Package className="w-3.5 h-3.5 text-[#727785]" />
                          <span>{sub.productCount ?? 0}</span>
                        </span>
                      </td>

                      <td className="px-5 py-3.5">
                        <button
                          type="button"
                          onClick={() => handleToggleStatus(sub)}
                          className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase transition-all ${
                            isActive
                              ? 'bg-emerald-100 text-emerald-800 hover:bg-emerald-200'
                              : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
                          }`}
                          title="Click to toggle status"
                        >
                          {isActive ? (
                            <>
                              <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                              <span>Active</span>
                            </>
                          ) : (
                            <>
                              <XCircle className="w-3 h-3 text-zinc-500" />
                              <span>Inactive</span>
                            </>
                          )}
                        </button>
                      </td>

                      <td className="px-5 py-3.5 text-[#727785]">
                        <div className="flex items-center gap-1 text-[11px]">
                          <Calendar className="w-3 h-3" />
                          <span>{sub.createdAt ? new Date(sub.createdAt).toLocaleDateString() : 'Initial'}</span>
                        </div>
                      </td>

                      <td className="px-5 py-3.5 text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          <button
                            type="button"
                            onClick={() => openEditModal(sub)}
                            className="p-1.5 text-[#555f6f] hover:text-[#6b38d4] hover:bg-purple-50 rounded-lg transition-colors"
                            title="Edit Subcategory"
                          >
                            <Edit2 className="w-3.5 h-3.5" />
                          </button>
                          <button
                            type="button"
                            onClick={() => setDeletingSubcategory(sub)}
                            className="p-1.5 text-[#ba1a1a] hover:bg-red-50 rounded-lg transition-colors"
                            title="Delete Subcategory"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ================= MODAL: ADD / EDIT SUBCATEGORY ================= */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-white rounded-2xl shadow-2xl border border-[#e2e2e2] w-full max-w-md overflow-hidden"
          >
            <div className="p-5 bg-[#f9f9f9] border-b border-[#eeeeee] flex items-center justify-between">
              <h3 className="font-['Montserrat'] font-bold text-base text-[#1a1c1c] flex items-center gap-2">
                <FolderTree className="w-4 h-4 text-[#6b38d4]" />
                <span>{editingSubcategory ? 'Edit Subcategory' : 'Add New Subcategory'}</span>
              </h3>
              <button
                type="button"
                onClick={() => setIsModalOpen(false)}
                className="w-7 h-7 rounded-full bg-[#eeeeee] flex items-center justify-center hover:bg-[#e2e2e2] text-[#424754]"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleSaveSubcategory} className="p-5 space-y-4">
              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1">
                  Parent Category <span className="text-red-500">*</span>
                </label>
                <select
                  required
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
                >
                  <option value="" disabled>
                    -- Select Category --
                  </option>
                  {categories.map((cat) => (
                    <option key={cat.id || cat._id} value={cat.id || cat._id}>
                      {cat.name} {cat.status === false ? '(Inactive)' : ''}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1">
                  Subcategory Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. T-Shirts, Hoodies, Coffee Mugs"
                  value={formData.name}
                  onChange={handleNameChange}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="text-xs font-bold text-[#1a1c1c]">
                    Slug / URL Identifier <span className="text-red-500">*</span>
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      setSlugAutoGenerated(true);
                      setFormData((prev) => ({ ...prev, slug: generateSlug(prev.name) }));
                    }}
                    className="text-[10px] text-[#6b38d4] hover:underline"
                  >
                    Auto-generate
                  </button>
                </div>
                <input
                  type="text"
                  required
                  placeholder="e.g. t-shirts, hoodies"
                  value={formData.slug}
                  onChange={(e) => {
                    setSlugAutoGenerated(false);
                    setFormData({ ...formData, slug: e.target.value.toLowerCase().replace(/\s+/g, '-') });
                  }}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs font-mono focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1">Description</label>
                <textarea
                  rows={2}
                  placeholder="Brief description of this subcategory..."
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-[#1a1c1c] block mb-1 flex items-center gap-1.5">
                  <ImageIcon className="w-3.5 h-3.5 text-[#727785]" />
                  <span>Image URL (Optional)</span>
                </label>
                <input
                  type="url"
                  placeholder="https://..."
                  value={formData.image}
                  onChange={(e) => setFormData({ ...formData, image: e.target.value })}
                  className="w-full px-3 py-2 bg-[#f9f9f9] border border-[#e2e2e2] rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-[#6b38d4]"
                />
              </div>

              <div className="flex items-center justify-between p-3 bg-[#f9f9f9] rounded-xl border border-[#e2e2e2]">
                <div>
                  <div className="text-xs font-bold text-[#1a1c1c]">Subcategory Status</div>
                  <div className="text-[11px] text-[#727785]">Visible in filters and product configuration</div>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    checked={formData.status}
                    onChange={(e) => setFormData({ ...formData, status: e.target.checked })}
                    className="sr-only peer"
                  />
                  <div className="w-9 h-5 bg-[#d0d3d8] peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-[#d0d3d8] after:border after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-[#6b38d4]"></div>
                </label>
              </div>

              <div className="flex gap-2 pt-3 border-t border-[#eeeeee]">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="flex-1 py-2 rounded-xl bg-[#eeeeee] hover:bg-[#e2e2e2] text-[#1a1c1c] text-xs font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 py-2 rounded-xl bg-[#6b38d4] hover:bg-[#582db5] text-white text-xs font-semibold flex items-center justify-center gap-1.5 shadow-sm transition-colors"
                >
                  {loading && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
                  <span>{editingSubcategory ? 'Save Changes' : 'Create Subcategory'}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ================= MODAL: DELETE PROTECTION / CONFIRMATION ================= */}
      {deletingSubcategory && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-white rounded-2xl shadow-2xl border border-[#e2e2e2] w-full max-w-md p-6 space-y-4"
          >
            <div className="w-12 h-12 rounded-full bg-red-100 text-red-600 flex items-center justify-center mx-auto">
              <AlertTriangle className="w-6 h-6" />
            </div>

            <div className="text-center space-y-1.5">
              <h3 className="font-['Montserrat'] font-bold text-base text-[#1a1c1c]">
                Delete Subcategory "{deletingSubcategory.name}"?
              </h3>
              <p className="text-xs text-[#555f6f] leading-relaxed">
                This will permanently remove the subcategory from the catalog.
              </p>
            </div>

            {/* Dependency Warning */}
            {(deletingSubcategory.productCount ?? 0) > 0 ? (
              <div className="p-3.5 bg-amber-50 border border-amber-200 rounded-xl space-y-2 text-xs text-amber-900">
                <div className="font-bold flex items-center gap-1.5 text-amber-800">
                  <AlertTriangle className="w-4 h-4 text-amber-600" />
                  <span>Product Dependency Detected</span>
                </div>
                <p className="text-[11px] leading-relaxed">
                  <strong>{deletingSubcategory.productCount}</strong> existing product(s) reference this subcategory.
                  Deletion is blocked to protect data integrity and avoid broken catalog listings.
                </p>
                <p className="text-[11px] text-amber-800 italic">
                  Please reassign these products to another subcategory before deleting.
                </p>
              </div>
            ) : (
              <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-xs text-emerald-800">
                No active products are assigned to this subcategory. It is safe to delete.
              </div>
            )}

            <div className="flex gap-2 pt-2">
              <button
                type="button"
                onClick={() => setDeletingSubcategory(null)}
                className="flex-1 py-2 rounded-xl bg-[#eeeeee] hover:bg-[#e2e2e2] text-[#1a1c1c] text-xs font-semibold"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={confirmDeleteSubcategory}
                disabled={isDeleting}
                className="flex-1 py-2 rounded-xl bg-[#ba1a1a] hover:bg-red-700 text-white text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors disabled:opacity-50"
              >
                {isDeleting && <RefreshCw className="w-3.5 h-3.5 animate-spin" />}
                <span>Delete Subcategory</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
